---
name: Packer Validate on Pull Requests

# Controls when the action will run.
# Triggers the workflow on push or pull request events but only for the main branch
on:
  # Workflow is triggered on pull requests
  pull_request:
    # Workflow will only be triggered for pull requests on "main" branch
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: webapp

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
      working-directory: ${{ env.working-directory }}
    - run: npm run build --if-present
      working-directory: ${{ env.working-directory }}
    - run: npm run test
      working-directory: ${{ env.working-directory }}